### ISSUE TITLE
Custom onClose event

### ISSUE THREAD

**Issue by IdrisHanafi** [asennikov/ember-g-map#126]
I have a g-map-marker and inside of it has a g-map-infowindow:

      {{#g-map-marker contextlat=37.7733 lng=-122.4067 as |markerContext|}}
                {{#g-map-infowindow markerContext openOn="mouseover" closeOn="customClose"}}
                    test infowindow
                {{/g-map-infowindow}}
            {{/g-map-marker}}

The infowindow opens up on mouseover and I am trying to get it to close on a custom function "customClose." The function customClose is pretty much a "mouseout" but with a 2 second delay. The part that I need help is to call that customClose function in the ember file. How do I go about fixing that? 

Thanks.

**Comment by steveszc** [comment]
Per the README, available options for closeOn are: `click`, `dblclick`, `rightclick`, `mouseover`, `mouseout`.  I don't believe what you're trying to do is possible using closeOn. 
You best bet may be to write your own version of the `g-map-infowindow` component (or extend the component) in order to implement this custom close logic that you require. You'll need to register a mouseout event listener on the infowindow and handle your custom mouseout logic there.

Please note: we generally aim to keep this issue tracker focused on specific issues with the addon, it is not really intended to answer general questions that might be better suited for Stack Overflow, the Ember Community Slack, or the Ember Discussion Forum.
