### ISSUE TITLE
Marker as function of address (in addition to lat/long)

### ISSUE THREAD

**Issue by FelixAkk** [asennikov/ember-g-map#13]
Hi!

I was wondering if something like this is possible:
```
{{g-map-marker context address="Delft, The Netherlands"}}
```
That would be a more user friendly way of entering a location in a lot of use cases (anything urban).

Thanks so much for making a working Google Maps component! I first stumbled (probably like most) upon https://github.com/huafu/ember-google-map, but sadly seems to have fallen out of maintenance. Perhaps you guys can work together on maturing your component?

**Comment by asennikov** [comment]
Hi @FelixAkk!

It's a good idea, I suppose I should implement something like that.

The only thing is that I don't want to increase complexity in current `{{g-map-marker}}`. Instead, I'm thinking about adding another `{{g-map-address-marker}}` component which will be using `{{g-map-marker}}` under the hood.

And of course if anybody has some spare time for this – PRs are welcomed and highly appreciated.

**Comment by FelixAkk** [comment]
That sounds great what you proposed! :) I'm still quite an Ember newbie, so for now I won't be able to make a PR, but when I've got some more experience and it's still open perhaps I can get back to it.

**Comment by asennikov** [comment]
Hey @FelixAkk, I've added `{{g-map-address-marker}}` component, check it out.

**Comment by FelixAkk** [comment]
Nice! :)

Not to bummer after your fine work, but it seems there's a bug where the map doesn't render when only containing address markers. When it contains also at least 1 lat/long marker everything works fine.

**Comment by asennikov** [comment]
Thx for catching it, I think it will be easy to fix.

**Comment by asennikov** [comment]
@FelixAkk I've looked into this issue and it looks like it's not exactly a bug, let me explain. 

First of all, I believe you are trying to show single `{{g-map-address-marker}}` on a map with `shouldFit` option set to true, right?

If my assumption is correct, then here is what happens: address marker doesn't appear on map immediately (because it requires some time to ask google places API for coordinates), while `shouldFit` option forces map to fit to all markers available at initialization (and it misses address marker, because it's still not present). As a result map shows nothing because it has no coordinates available.

To fix this you have 2 options:
1) replace `shouldFit` with `lat`, `lng` and `zoom` for map to start with some point;
2) replace `shouldFit=true` with `markersFitMode="live"` to let map observe any change to markers and adopt to them.

I've updated sample (dummy) application in `/tests` folder as a reference. Here's some additional info too - https://github.com/asennikov/ember-g-map#map-fits-to-show-all-initial-markers

**Comment by FelixAkk** [comment]
That's a great explanation actually :) I suspected something with the asynchronous nature of resolving addresses. `markersFitMode="live"` will do just fine while keeping the fit dynamic (I like not having to worry about forgetting to update such things when for example adding new elements). Thanks a lot! :)
